### PR TITLE
Upgrade ckb dependencies to `v0.111.0`

### PR DESCRIPTION
**Pull request by eval-exec**
This PR is based on nervosnetwork/ckb-sdk-rust#80

- [x] Support `Data2`

### CODE REVIEW

**Comment by doitian** [comment]
> Replace 0.111.0-rc3 by 0.111.0 when they are ready

CKB will package ckb-cli, so ckb-cli cannot wait for the stable release of CKB.

**Comment by eval-exec** [comment]
> > Replace 0.111.0-rc3 by 0.111.0 when they are ready
> 
> CKB will package ckb-cli, so ckb-cli cannot wait for the stable release of CKB.

OK

**Comment by eval-exec** [comment]
Please trigger the CI action. @doitian

**Comment by eval-exec** [comment]
Waiting CI jobs result.

**Review by doitian — APPROVED** [review]

**Comment by eval-exec** [comment]
The integration-test has passed on ubuntu-latest. I think we can merge this PR and package ckb-cli v1.5.0 now. @doitian

**Pull request merged**
