### PR TITLE
refactor: Deduplicate `get_keystore_signer`

### PR DESCRIPTION
**Pull request by Ericson2314**
Contains #244

### CODE REVIEW

**Comment by TheWaWaR** [comment]
Please rebase.

**Comment by Ericson2314** [comment]
I will also get rid rid of the `AsRef` stuff which is overkill since it is taking `&P` not `P`; easier to just take `&[ChildNumber]`, which as fine as `DerivationPath: AsRef<&[ChildNumber]>` too.

**Comment by TheWaWaR** [comment]
`AsRef<[ChildNumber]>` is more generic, and we copy the code for `bitcoin-rust`, better just keep that way.

**Comment by Ericson2314** [comment]
@TheWaWaR Well, or what it's worth, it ended up biting me later when I needed to make a trait object and the polymorphism made the method unusable, and so I had to change it to `&[ChildNumber]`.

**Comment by TheWaWaR** [comment]
> @TheWaWaR Well, or what it's worth, it ended up biting me later when I needed to make a trait object and the polymorphism made the method unusable, and so I had to change it to `&[ChildNumber]`.
That's why I prefer avoid generic. Rust trait sometimes can not work well with generic.

> But if you like it, I'll rebase this one as-is for now then, and then when we look over all the SDK changes for the ledger support later we can worry about that.

It's OK to change the API to `&[ChildNumber]` here, better rebase first.

**Comment by Ericson2314** [comment]
Closing beause things have changed on our client fork and the plan to reconcile is different.

**Pull request closed without merging**
